#!/usr/bin/awk -f

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2014 Osiris Alejandro Gomez <osiux@osiux.com.ar>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

NR == 1 {
  max=$1;
  min=$1;
  sum=0;
}

{
  if ($1>max)
  {
    max=$1;
  }
  if ($1<min)
  {
    min=$1;
  }
  sum+=$1;
}
  
END {
  printf "Min: %f\tMax: %f\tAvg: %f\tSum: %f\tTotal: %d\n",
         min, max, sum/NR, sum, NR
}

