#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2014 Osiris Alejandro Gomez <osiux@osiux.com.ar>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

if [ -z $1 ]
then
  DATE=$(date +%Y-%m-%d)
else
  DATE=$1
fi

echo $DATE
CLOCK="CLOCK: \["$DATE

cd ~/org
egrep "$CLOCK" *.org | tr "[]" " " | sed s/".org"//g | awk 'function minutos(t) {split(t,Arr,":");return Arr[1]*60+Arr[2]}{printf "%s %s\t%s\t%s\t%s\n",$5,$9,$11,minutos($11),$1}' | sort -n | sed s/:$//g

