#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2022 Osiris Alejandro Gomez <osiux@osiux.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

if [[ ! -t 0 ]]
then
  TMPI="$(mktemp)"

  true > "$TMPI"

  while IFS= read -r PIPED_INPUT
  do
    echo "$PIPED_INPUT" >> "$TMPI"
  done

fi

[[ -e "$TMPI" ]] && FILE="$(cat "$TMPI")"
[[ -z "$1"    ]] || FILE="$1"
[[ -e "$FILE" ]] || exit 1

YYYYMMDD='[0-9]{4}-[0-9]{2}-[0-9]{2}'
YYYY='[0-9]{4}'

DATE="$(grep -E '^\#\+DATE:' "$FILE" | head -1 | grep -Eo "$YYYYMMDD")"

[[ -z "$DATE" ]] && DATE="$(echo "$FILE" | grep -Eo "$YYYYMMDD")"
[[ -z "$DATE" ]] && DATE="$(echo "$FILE" | grep -Eo "$YYYY")"
[[ -z "$DATE" ]] && DATE="$(date +%F)"

echo "$DATE"
