#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2014 Osiris Alejandro Gomez <osiux@osiux.com.ar>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

source bin-common

if [ -z $1 ]
then
  DAY=$($DATE +%Y-%m-%d)
else
  DAY=$1
fi

cd $ORG

if [ -z $2 ]
then
  $EGREP "CLOCK: \[$DAY.*[0-9]+$" *.org | $TR "[]" " " | $AWK '{print $5,$9,$1}' | $SED s/".org:"//g | $SORT -k3
else
  $EGREP "CLOCK: \[$DAY.*[0-9]+$" $2 | $TR "[]" " " | $AWK '{print $4,$8,$2}' | $SED s/".org:"//g | $SORT -k3
fi



