#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2021 Osiris Alejandro Gomez <osiux@osiux.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

if [[ ! -t 0 ]]
then
  TMPI="$(mktemp)"

  true > "$TMPI"

  while IFS= read -r PIPED_INPUT
  do
    echo "$PIPED_INPUT" >> "$TMPI"
  done

fi

function die()
{
  echo >&2 "$1"
  exit 1
}

function get_og_image()
{

grep og:image "$FILE" \
  | grep -Eo 'content=".*"' \
  | tr -d '"' \
  | grep -Eo 'img/.*$'

}

[[ -e "$TMPI" ]] && FILE="$(cat "$TMPI")"
[[ -z "$1"    ]] || FILE="$1"
[[ -f "$FILE" ]] || die "NOT FOUND FILE $FILE"

REGEX_IMG='file:img.*(jpg|gif|png)'

IMG="$(grep -E "$REGEX_IMG" "$FILE" \
  | head -1                         \
  | cut -d: -f2                     \
  | cut -d ']' -f1)"

DIR="$(dirname "$FILE")"
OG="$(get_og_image)"
[[ -f "$DIR/$OG" ]] && IMG="$OG"

echo "$IMG"
