#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2013 Osiris Alejandro Gomez <osiux@osiux.com.ar>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

cd ~/org
YEAR=$(date +%Y)
MONTH=$(date +%m)
DAYS=$(egrep -ho "CLOCK:(.*)$YEAR-$MONTH-[0-9]{2}" *.org | awk '{print $2}' | tr -d "[" | sort -u)
FILES=$(egrep -l "CLOCK:(.*)$YEAR-$MONTH-[0-9]{2}" *.org | sort -u)

DAT=org-task-by-day.dat

echo -n dia$'\t' >$DAT
for F in $FILES
do
    echo -n $(basename $F .org)$'\t'min$'\t' >>$DAT
done
echo -n $'\n' >>$DAT

for DAY in $DAYS
do
    SEP='\t'
    for F in $FILES
    do
        grep "CLOCK: \[$DAY" $F | tr "[]" " " | awk '{split($10,a,":"); print $2,$4,a[1]*60+a[2]}' | sort | while read T
        do
            START=$(echo $T | awk '{print $2}')
            MINUTES=$(echo $T | awk '{print $3}')
            echo $DAY$SEP$START$'\t'$MINUTES >>$DAT
        done
        TAB=$'\t'
        #SEP=$SEP$TAB+'0'$TAB
        SEP=$SEP'0'$'\t'0$'\t'
    done
done
echo $DAT
