#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2021 Osiris Alejandro Gomez <osiux@osiux.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC2001

if [[ ! -t 0 ]]
then
  TMPI="$(mktemp)"

  true > "$TMPI"

  while IFS= read -r PIPED_INPUT
  do
    echo "$PIPED_INPUT" >> "$TMPI"
  done

fi

[[ -e "$TMPI" ]] && FILE="$(cat "$TMPI")"
[[ -z "$1"    ]] || FILE="$1"
[[ -e "$FILE" ]] || exit 1

function get_locale_lang()
{
  env | grep '^LANG=' | cut -d '=' -f2 | cut -d '.' -f1
}

function defaults()
{

[[ -n "$LOCALE"      ]] || LOCALE="$(get_locale_lang)"
[[ -n "$SITE_NAME"   ]] || SITE_NAME='OSiUX'
[[ -n "$TYPE"        ]] || TYPE='article'

[[ -n "$AUTHOR"      ]] || AUTHOR="$(org-author "$FILE")"
[[ -n "$DATE"        ]] || DATE="$(org-date "$FILE")"
[[ -n "$DESCRIPTION" ]] || DESCRIPTION="$(org-description "$FILE")"
[[ -n "$IMAGE"       ]] || IMAGE="$(image "$FILE")"

}

function meta2head()
{

printf "%s   <meta property=\"og:%s\" content=\"%s\" />\n" \
       '#+HTML_HEAD:' "$1" "$2"

}

function image()
{

REGEX_IMG='file:img.*(jpg|gif|png)'

IMG="$(grep -E "$REGEX_IMG" "$1" \
  | head -1                      \
  | cut -d: -f2                  \
  | cut -d ']' -f1)"

OG="$(echo "$IMG" | sed 's/^img/og/g')"

[[ -e "$OG" ]] && IMG="$OG"

echo "$IMG"

}

function opengraph()
{

meta2head 'title'     "$(org-title "$FILE")"

[[ -z "$DESCRIPTION" ]] || meta2head 'description' "$DESCRIPTION"

meta2head 'type'                   "$TYPE"

if [[ "$TYPE" = 'article' ]]
then

meta2head 'article:published_time' "$DATE"
meta2head 'article:author'         "$AUTHOR"

fi
meta2head 'url'                    "https://osiux.com/${FILE/\.org/\.html}"
meta2head 'site_name'              "$SITE_NAME"
meta2head 'locale'                 "$LOCALE"

[[ -z "$IMAGE" ]] || meta2head 'image' "https://osiux.com/$IMAGE"
printf "\n"

}

function main()
{

defaults
opengraph

}

main
