#!/bin/bash

     cd ~/org
     YEAR=$(date +%Y)
     MONTH=$(date +%m)
     DAYS=$(egrep -ho "CLOCK:(.*)$YEAR-$MONTH-[0-9]{2}" *.org | awk '{print $2}' | tr -d "[" | sort -u)
     FILES=$(egrep -l "CLOCK:(.*)$YEAR-$MONTH-[0-9]{2}" *.org | sort -u)

     #YEAR=2011
     #DAYS=$(egrep -ho "CLOCK:(.*)$YEAR-[0-9]{2}-[0-9]{2}" *.org | awk '{print $2}' | tr -d "[" | sort -u)
     #FILES=$(egrep -l "CLOCK:(.*)$YEAR-[0-9]{2}-[0-9]{2}" *.org | sort -u)

     DAT=org-task-by-day.dat

     echo -n 'dia\t' >$DAT
     for F in $FILES
     do
       echo -n $(basename $F .org)'\tmin\t' >>$DAT
     done
     echo -n '\n' >>$DAT

     for DAY in $DAYS
     do       
       SEP='\t'
       for F in $FILES
       do
         grep "CLOCK: \[$DAY" $F | tr "[]" " " | awk '{split($10,a,":"); print $2,$4,a[1]*60+a[2]}' | sort | while read T
         do
           START=$(echo $T | awk '{print $2}')
           MINUTES=$(echo $T | awk '{print $3}')
           echo $DAY$SEP$START'\t'$MINUTES >>$DAT
         done
         SEP=$SEP'0\t0\t'
       done
     done
     echo $DAT
   #+end_src

   #+begin_src gnuplot :var data='org-task-by-day.dat' :file org-task-by-day.png
   reset
   #set terminal png size 640, 480
   set terminal png size 1024, 768
   set lmargin 5
   set bmargin 5
   set rmargin 16
   set title "Orgmode Task by Day" font "Inconsolata,10"
   set xdata time
   set ydata time

   set timefmt x "%Y-%m-%d"
   #set xrange ["2012-01-01":"2012-01-33"]
   set format x "%Y/%m/%d" font "Inconsolata,8"

   set timefmt y "%H:%M"

   set format y "%H:%M"
   #set format x "%d/%m/%Y" font "Inconsolata,8"
   set yrange ["06:01":"19:59"]
   set key outside font "Inconsolata,10"
   set xtics 60*60*24 font "Inconsolata,8" nomirror rotate by right at 0.5,0
   set ytics font "Inconsolata,8" nomirror
   set mytics
   unset mxtics
   #set autoscale x
   f=`ls ~/org/*.org | wc -l`
   plot for [i=2:f:2] data u 1:i:(0):(column(i+1)*60) with vec lw 20 nohead ti col(i)

