#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2014 Osiris Alejandro Gomez <osiux@osiux.com.ar>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

cd ~/org

for i in *.org
do
    egrep "^\*(.*)SOMEDAY " $i | sed -e s/[a-z:@]*:$//g | sed s/[*]*\ SOMEDAY\ //g | while read j
    do
        echo "  - [ ] "$j
    done | sort >/tmp/$i
    
    l=$(wc -l /tmp/$i | awk '{print $1}')

    if [ $l -ne 0 ]
    then
        echo "* $i [0/$l]" 
        cat /tmp/$i
    fi
done

